---
name: Deploy Image
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-24.04
    needs: check-requirements
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -t lanlords/bfbc2-master:latest .
      - name: Push Image
        run: docker push lanlords/bfbc2-master:latest

  update-readme:
    name: Update Readme
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: lanlords/bfbc2-master
